# Generated by Django 5.2.7 on 2025-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("region", models.CharField(blank=True, max_length=100)),
                ("grape", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
